Downgrade lodash, since the current version causes build errors.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12773

We get errors like this when compiling now:

```
node_modules/@types/lodash/modules.d.ts(8,24): error TS2339: Property 'ary' does not exist on type 'UnderscoreStatic'.
node_modules/@types/lodash/modules.d.ts(20,29): error TS2339: Property 'assignIn' does not exist on type 'UnderscoreStatic'.
```
and many more. Deleting the `/// <reference path="modules.d.ts" />` line in @types/lodash/index.d.ts makes everything compile again.