Replaced npm with yarn in the dev install script
With the dependency to jupyterlab, using npm caused the following installation
errors:

`base.ts(5,27): error TS2307: Cannot find module '@jupyterlab/services'`

It is discovered when install on python 3.6.2 on a MacOS.

Fixes #1827